app:
  base-url: http://${FRONT_END_URL}:3000
  document:
    max-size-threshold-mb: 25MB
  ocr:
    data-path: /usr/share/tesseract-ocr/5/tessdata
    minimum-text-length: 50  # Minimum text length to consider a PDF as text-based
    chunk-size: 10
    max-threads: 4
    temp-dir: /tmp/ocr
    dpi: 300
    image-type: RGB
  pdf:
    quality-threshold: 0.8
    min-text-density: 0.01
  email:
    batch-size: 50  # Number of emails per batch

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}:27017/dms?authSource=admin
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/postgres?currentSchema=dms
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    publisher-confirm-type: correlated
    publisher-returns: true

  mail:
    host: ${MAIL_SERVER_HOST}
    port: 587
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail-sender:
  from-email: no-reply@dms.com

opensearch:
  host: ${OPENSEARCH_URL}
  port: 9200
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  scheme: https
  aws: true

# RabbitMQ
rabbitmq:
  exchanges:
    internal: internal.exchange
    dlx: dead.letter.exchange
    notification: notification.exchange
  queues:
    document-sync: document-sync.queue
    document-sync-dlq: document-sync.dlq
    notification: notification.queue
    notification-dlq: notification.dlq
    otp: notification.otp.queue
    password-reset: password-reset.queue
  routing-keys:
    internal-document-sync: internal.document-sync.routing-key
    notification: notification.email.routing-key
    dlq: dead.letter.routing-key
    otp: notification.otp.email.routing-key
    password-reset: notification.password-reset.routing-key

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION:ap-southeast-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    temp-dir: ${java.io.tmpdir}/dms-processor