server:
  port: 8084
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data:
          elasticsearch: DEBUG
      elasticsearch: DEBUG
spring:
  application:
    name: processor-service
  profiles:
    active: local

app:
  file-storage:
    type: S3  # Options: LOCAL, S3
    local:
      upload-dir: "uploads"
      temp-dir: "temp"
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME:dms-doc-s3-dev}
      region: ${AWS_REGION:ap-southeast-1}
      access-key: ${AWS_ACCESS_KEY:test}
      secret-key: ${AWS_SECRET_KEY:test}