app:
  frontend:
    url: http://116.111.185.170:3000

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://10.0.3.23:8081/eureka/
  instance:
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20