app:
  eureka:
    url: ${EUREKA_URI}
  auth-service:
    api-key: ${AUTH_SERVICE_API_KEY:document-search-api-key}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_ENDPOINT_URL}
          jwk-set-uri: ${AUTH_SERVICE_ENDPOINT_URL}/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/dms?authSource=admin

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_URI}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

opensearch:
  host: ${RESOURCE_URL:100.104.245.71}
  port: 9200
  username: admin
  password: admin
  scheme: http
  aws: false