app:
  eureka:
    url: http://localhost:8081
  document:
    storage:
      path: ./document/storage
    max-size-mb: 50MB
    thumbnail:
      width: 300
      height: 200
    placeholder:
      processing: classpath:placeholders/processing-thumbnail.png
      error: classpath:placeholders/error-thumbnail.png

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${app.document.max-file-size:50MB}
      max-request-size: ${app.document.max-file-size:50MB}
      file-size-threshold: 2MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  data:
    mongodb:
      authentication-database: admin
      username: mongodb
      password: mongodbpw
      database: dms
      port: 27017
      host: 127.0.0.1
  rabbitmq:
    addresses: localhost:5672

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# Elasticsearch
elasticsearch:
  host: 127.0.0.1
  port: 9200
  username: elastic  # Default username for Elasticsearch 8.x
  password: "NX9DYn+_4WSXRmHwymTo"

model-service:
  url: http://localhost:8000
  api-key: ${MODEL_SERVICE_API_KEY:your-secret-key}

resilience4j:
  circuitbreaker:
    instances:
      modelService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      modelService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
