app:
  eureka:
    url: ${EUREKA_URI}
  auth-service:
    api-key: ${AUTH_SERVICE_API_KEY:document-search-api-key}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_ENDPOINT_URL}
          jwk-set-uri: ${AUTH_SERVICE_ENDPOINT_URL}/.well-known/jwks.json
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/postgres?currentSchema=dms
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/dms?authSource=admin

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOST}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

opensearch:
  host: ${OPENSEARCH_URL}
  port: 9200
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  scheme: http
  aws: false