app:
  eureka:
    url: http://localhost:8081
  auth-service:
    api-key: ${AUTH_SERVICE_API_KEY:document-search-api-key}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  data:
    mongodb:
      authentication-database: admin
      username: mongodb
      password: mongodbpw
      database: dms
      port: 27017
      host: 127.0.0.1
  rabbitmq:
    addresses: localhost:5672

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# Elasticsearch
elasticsearch:
  host: 127.0.0.1
  port: 9200
  username: elastic  # Default username for Elasticsearch 8.x
  password: "NX9DYn+_4WSXRmHwymTo"