app:
  eureka:
    url: http://localhost:8081
  auth-service:
    api-key: ${AUTH_SERVICE_API_KEY:document-search-api-key}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb://mongodb:mongodbpw@localhost:27017/

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

opensearch:
  host: localhost
  port: 9200
  username: admin
  password: admin
  scheme: http
  aws: false