app:
  eureka:
    url: http://${EUREKA_URI}:8081
  auth-service:
    api-key: ${AUTH_SERVICE_API_KEY:document-search-api-key}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVICE_ENDPOINT_URL}:8082
          jwk-set-uri: http://${AUTH_SERVICE_ENDPOINT_URL}:8082/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}:27017/dms?authSource=admin

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_URI}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

opensearch:
  host: ${OPENSEARCH_URL}
  port: 9200
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  scheme: https
  aws: true