server:
  port: 8083
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data:
          elasticsearch: DEBUG
      elasticsearch: DEBUG

spring:
  application:
    name: document-search-service
  profiles:
    active: local
  cloud:
    discovery:
      enabled: true