app:
  eureka:
    url: http://localhost:8081
  document:
    storage:
      path: ./document/storage
    max-size-threshold-mb: 25MB
    max-size-mb: 50MB
    thumbnail:
      width: 300
      height: 200
  ocr:
    data-path: /usr/share/tesseract-ocr/5/tessdata
    minimum-text-length: 50  # Minimum text length to consider a PDF as text-based
    chunk-size: 10
    max-threads: 4
    temp-dir: /tmp/ocr
    dpi: 300
    image-type: RGB
  pdf:
    quality-threshold: 0.8
    min-text-density: 0.01

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${app.document.max-file-size:50MB}
      max-request-size: ${app.document.max-file-size:50MB}
      file-size-threshold: 2MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  data:
    mongodb:
      authentication-database: admin
      username: mongodb
      password: mongodbpw
      database: dms
      port: 27017
      host: localhost
  rabbitmq:
    addresses: localhost:5672

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10