package com.dms.processor.enums;

public enum EventType {
    SYNC_EVENT,
    UPDATE_EVENT,
    UPDATE_EVENT_WITH_FILE,
    DELETE_EVENT,
    REVERT_EVENT,
    FAVORITE_NOTIFICATION,
    DOCUMENT_REPORT_PROCESS_EVENT,
    COMMENT_REPORT_PROCESS_EVENT,
}