app:
  eureka:
    url: http://localhost:8081
  auth-service:
    api-key: ${AUTH_SERVICE_API_KEY:document-interaction-api-key}
  document:
    storage:
      path: ./document/storage
    max-size-mb: 50MB
    thumbnail:
      width: 300
      height: 200
    placeholder:
      processing: classpath:placeholders/processing-thumbnail.png
      error: classpath:placeholders/error-thumbnail.png

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${app.document.max-file-size:50MB}
      max-request-size: ${app.document.max-file-size:50MB}
      file-size-threshold: 2MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=dms
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: mongodb://mongodb:mongodbpw@localhost:27017/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

model-service:
  url: http://localhost:8000
  api-key: ${MODEL_SERVICE_API_KEY:your-secret-key}

resilience4j:
  circuitbreaker:
    instances:
      modelService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      modelService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION:ap-southeast-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}