server:
  port: 8085
  error:
    include-message: always

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#        security: DEBUG

spring:
  application:
    name: document-interaction-service
  profiles:
    active: local
  cloud:
    discovery:
      enabled: true